package com.katariastoneworld.apis.service.audit;

import com.katariastoneworld.apis.config.AuditReportProperties;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Professional ERP-style PDF drawing primitives for audit reports. */
public final class AuditReportLayoutEngine {

    private static final DateTimeFormatter DT_FMT =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss", Locale.ROOT);

    private AuditReportLayoutEngine() {}

    public static void drawPremiumCover(PDDocument doc,
                                        PDPage page,
                                        AuditReportPdfFonts fonts,
                                        AuditReportProperties props,
                                        AuditReportSnapshot snapshot,
                                        AuditReportJob job,
                                        java.time.LocalDateTime generatedAt,
                                        long grandTotal) throws IOException {
        float w = page.getMediaBox().getWidth();
        float h = page.getMediaBox().getHeight();
        try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
            fillRect(cs, 0, 0, w, h, AuditReportTheme.PRIMARY_DARK);
            fillRect(cs, 0, h * 0.55f, w, h * 0.45f, AuditReportTheme.PRIMARY);

            // Watermark text
            text(cs, fonts.regular(), 48, w / 2 - 120, h / 2 - 40, props.getCompanyName(),
                    new Color(255, 255, 255, 30));

            drawLogo(doc, cs, props, w - AuditReportTheme.MARGIN - 90, h - AuditReportTheme.MARGIN - 80, 80);

            float y = h - AuditReportTheme.MARGIN - 120;
            text(cs, fonts.bold(), 28, AuditReportTheme.MARGIN, y, props.getCompanyName(), AuditReportTheme.WHITE);
            y -= 36;
            text(cs, fonts.bold(), 22, AuditReportTheme.MARGIN, y, "Application Audit Report", AuditReportTheme.GOLD_LIGHT);
            y -= 28;
            text(cs, fonts.regular(), 13, AuditReportTheme.MARGIN, y, props.getApplicationName(), AuditReportTheme.WHITE);

            // Confidential badge
            float badgeW = 110;
            fillRoundedRect(cs, w - AuditReportTheme.MARGIN - badgeW, AuditReportTheme.MARGIN + 10, badgeW, 22, 6,
                    AuditReportTheme.ERROR);
            text(cs, fonts.bold(), 8, w - AuditReportTheme.MARGIN - badgeW + 12, AuditReportTheme.MARGIN + 16,
                    "CONFIDENTIAL", AuditReportTheme.WHITE);

            y -= 50;
            fillRect(cs, AuditReportTheme.MARGIN, y - 2, w - AuditReportTheme.MARGIN * 2, 2, AuditReportTheme.GOLD);

            y -= 30;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Report ID", snapshot.getReportId());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Generated On", DT_FMT.format(generatedAt));
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Generated By",
                    job.getGeneratedByName() + "  ·  " + job.getGeneratedByEmail());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Branch / Location", snapshot.getBranch());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Report Period", snapshot.getReportPeriod());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Application Version", props.getApplicationVersion());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Database", snapshot.getDatabaseVersion());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Report Version", props.getReportVersion());
            y -= 22;
            drawMetaLine(cs, fonts, AuditReportTheme.MARGIN, y, "Total Records",
                    String.format(Locale.ROOT, "%,d", grandTotal));

            text(cs, fonts.regular(), 9, AuditReportTheme.MARGIN, AuditReportTheme.MARGIN + 8,
                    "Enterprise audit snapshot — all modules, summaries, and detailed records included.",
                    AuditReportTheme.WHITE);
        }
    }

    public static float drawSectionBanner(PDPageContentStream cs,
                                         PDFont bold,
                                         float x,
                                         float y,
                                         float width,
                                         String title,
                                         String subtitle) throws IOException {
        fillRoundedRect(cs, x, y - 28, width, 32, 6, AuditReportTheme.PRIMARY);
        text(cs, bold, 14, x + 12, y - 10, title, AuditReportTheme.WHITE);
        if (subtitle != null && !subtitle.isBlank()) {
            text(cs, bold, 8, x + 12, y - 22, subtitle, AuditReportTheme.GOLD_LIGHT);
        }
        return y - 40;
    }

    public static float drawKpiGrid(PDPageContentStream cs,
                                    AuditReportPdfFonts fonts,
                                    float startY,
                                    float pageWidth,
                                    List<AuditReportSnapshot.KpiCard> kpis,
                                    int startIndex) throws IOException {
        float usable = pageWidth - AuditReportTheme.MARGIN * 2;
        int cols = 3;
        float cardW = (usable - AuditReportTheme.KPI_GAP * (cols - 1)) / cols;
        float x = AuditReportTheme.MARGIN;
        float y = startY;
        int col = 0;
        for (int i = startIndex; i < kpis.size(); i++) {
            AuditReportSnapshot.KpiCard kpi = kpis.get(i);
            Color accent = accentColor(kpi.getAccent());
            fillRoundedRect(cs, x, y - AuditReportTheme.KPI_CARD_H, cardW, AuditReportTheme.KPI_CARD_H, 8,
                    AuditReportTheme.WHITE);
            strokeRoundedRect(cs, x, y - AuditReportTheme.KPI_CARD_H, cardW, AuditReportTheme.KPI_CARD_H, 8,
                    AuditReportTheme.NEUTRAL_BORDER);
            fillRect(cs, x, y - AuditReportTheme.KPI_CARD_H, 4, AuditReportTheme.KPI_CARD_H, accent);
            text(cs, fonts.regular(), 8, x + 12, y - 18, kpi.getLabel(), AuditReportTheme.TEXT_MUTED);
            text(cs, fonts.bold(), 12, x + 12, y - 36, kpi.getValue(), AuditReportTheme.TEXT_PRIMARY);
            col++;
            if (col >= cols) {
                col = 0;
                x = AuditReportTheme.MARGIN;
                y -= AuditReportTheme.KPI_CARD_H + AuditReportTheme.KPI_GAP;
            } else {
                x += cardW + AuditReportTheme.KPI_GAP;
            }
            if (y < AuditReportTheme.MARGIN + AuditReportTheme.FOOTER_H + AuditReportTheme.KPI_CARD_H + 20) {
                return -(i + 1); // signal need new page, return next index as negative
            }
        }
        return y - AuditReportTheme.SECTION_GAP;
    }

    public static float drawInsightCards(PDPageContentStream cs,
                                         AuditReportPdfFonts fonts,
                                         float y,
                                         float pageWidth,
                                         List<AuditReportSnapshot.InsightCard> insights) throws IOException {
        float usable = pageWidth - AuditReportTheme.MARGIN * 2;
        int cols = 2;
        float cardW = (usable - AuditReportTheme.KPI_GAP) / cols;
        float x = AuditReportTheme.MARGIN;
        int col = 0;
        for (AuditReportSnapshot.InsightCard insight : insights) {
            fillRoundedRect(cs, x, y - 38, cardW, 40, 6, AuditReportTheme.GOLD_LIGHT);
            strokeRoundedRect(cs, x, y - 38, cardW, 40, 6, AuditReportTheme.NEUTRAL_BORDER);
            text(cs, fonts.bold(), 8, x + 10, y - 14, insight.getTitle(), AuditReportTheme.PRIMARY);
            text(cs, fonts.regular(), 7.5f, x + 10, y - 28, truncate(insight.getDetail(), 55),
                    AuditReportTheme.TEXT_PRIMARY);
            col++;
            if (col >= cols) {
                col = 0;
                x = AuditReportTheme.MARGIN;
                y -= 48;
            } else {
                x += cardW + AuditReportTheme.KPI_GAP;
            }
        }
        return y - AuditReportTheme.SECTION_GAP;
    }

    public static float drawKeyValuePanel(PDPageContentStream cs,
                                          AuditReportPdfFonts fonts,
                                          float y,
                                          float pageWidth,
                                          String title,
                                          Map<String, String> entries) throws IOException {
        float w = pageWidth - AuditReportTheme.MARGIN * 2;
        y = drawSectionBanner(cs, fonts.bold(), AuditReportTheme.MARGIN, y, w, title, null);
        fillRoundedRect(cs, AuditReportTheme.MARGIN, y - entries.size() * 16 - 16, w, entries.size() * 16 + 16, 8,
                AuditReportTheme.NEUTRAL_BG);
        strokeRoundedRect(cs, AuditReportTheme.MARGIN, y - entries.size() * 16 - 16, w, entries.size() * 16 + 16, 8,
                AuditReportTheme.NEUTRAL_BORDER);
        float rowY = y - 14;
        for (Map.Entry<String, String> e : entries.entrySet()) {
            text(cs, fonts.bold(), 9, AuditReportTheme.MARGIN + 14, rowY, e.getKey(), AuditReportTheme.TEXT_MUTED);
            text(cs, fonts.regular(), 9, AuditReportTheme.MARGIN + w * 0.45f, rowY, e.getValue(),
                    AuditReportTheme.TEXT_PRIMARY);
            rowY -= 16;
        }
        return rowY - AuditReportTheme.SECTION_GAP;
    }

    public static float drawBarChart(PDPageContentStream cs,
                                     AuditReportPdfFonts fonts,
                                     float y,
                                     float pageWidth,
                                     String title,
                                     List<AuditReportSnapshot.ChartBar> bars) throws IOException {
        if (bars == null || bars.isEmpty()) {
            text(cs, fonts.regular(), 9, AuditReportTheme.MARGIN, y, title + ": No data", AuditReportTheme.TEXT_MUTED);
            return y - 24;
        }
        float w = pageWidth - AuditReportTheme.MARGIN * 2;
        y = drawSectionBanner(cs, fonts.bold(), AuditReportTheme.MARGIN, y, w, title, null);
        double max = bars.stream().mapToDouble(AuditReportSnapshot.ChartBar::getValue).max().orElse(1);
        float barAreaW = w - 120;
        float rowY = y;
        for (AuditReportSnapshot.ChartBar bar : bars) {
            float barW = (float) (bar.getValue() / max * barAreaW);
            text(cs, fonts.regular(), 7, AuditReportTheme.MARGIN + 4, rowY - 10,
                    truncate(bar.getLabel(), 14), AuditReportTheme.TEXT_MUTED);
            fillRoundedRect(cs, AuditReportTheme.MARGIN + 110, rowY - 14, Math.max(2, barW), 10, 3, AuditReportTheme.TEAL);
            text(cs, fonts.regular(), 7, AuditReportTheme.MARGIN + 115 + barW + 4, rowY - 10,
                    formatChartValue(bar.getValue()), AuditReportTheme.TEXT_PRIMARY);
            rowY -= 18;
        }
        return rowY - 8;
    }

    public static float drawPageHeader(PDPageContentStream cs,
                                       PDPage page,
                                       AuditReportPdfFonts fonts,
                                       AuditReportProperties props,
                                       int pageNumber,
                                       String sectionTitle,
                                       java.time.LocalDateTime generatedAt) throws IOException {
        float w = page.getMediaBox().getWidth();
        float h = page.getMediaBox().getHeight();
        fillRect(cs, 0, h - AuditReportTheme.HEADER_H, w, AuditReportTheme.HEADER_H, AuditReportTheme.PRIMARY);
        fillRect(cs, 0, h - AuditReportTheme.HEADER_H, 4, AuditReportTheme.HEADER_H, AuditReportTheme.GOLD);
        text(cs, fonts.bold(), 9, AuditReportTheme.MARGIN, h - 14, props.getCompanyName(), AuditReportTheme.WHITE);
        text(cs, fonts.bold(), 9, w / 2 - 50, h - 14, "Audit Report", AuditReportTheme.WHITE);
        text(cs, fonts.regular(), 8, w - AuditReportTheme.MARGIN - 140, h - 14, sectionTitle, AuditReportTheme.GOLD_LIGHT);
        drawPageFooter(cs, page, fonts, props, pageNumber, generatedAt);
        return h - AuditReportTheme.HEADER_H - 16;
    }

    public static void drawPageFooter(PDPageContentStream cs,
                                      PDPage page,
                                      AuditReportPdfFonts fonts,
                                      AuditReportProperties props,
                                      int pageNumber,
                                      java.time.LocalDateTime generatedAt) throws IOException {
        float w = page.getMediaBox().getWidth();
        fillRect(cs, 0, 0, w, AuditReportTheme.FOOTER_H, AuditReportTheme.NEUTRAL_BG);
        strokeLine(cs, AuditReportTheme.MARGIN, AuditReportTheme.FOOTER_H + 2, w - AuditReportTheme.MARGIN,
                AuditReportTheme.FOOTER_H + 2, AuditReportTheme.NEUTRAL_BORDER);
        text(cs, fonts.regular(), 7, AuditReportTheme.MARGIN, 8, props.getCompanyName(), AuditReportTheme.TEXT_MUTED);
        text(cs, fonts.regular(), 7, w / 2 - 60, 8,
                "Generated " + DT_FMT.format(generatedAt) + "  ·  v" + props.getReportVersion(),
                AuditReportTheme.TEXT_MUTED);
        text(cs, fonts.bold(), 7, w - AuditReportTheme.MARGIN - 70, 8,
                "Page " + pageNumber + "  ·  CONFIDENTIAL", AuditReportTheme.PRIMARY);
    }

    public static void drawTableTitle(PDPageContentStream cs,
                                      AuditReportPdfFonts fonts,
                                      float y,
                                      String title,
                                      String tableName,
                                      long rowCount,
                                      boolean continued) throws IOException {
        text(cs, fonts.bold(), 11, AuditReportTheme.MARGIN, y, title, AuditReportTheme.PRIMARY);
        text(cs, fonts.regular(), 8, AuditReportTheme.MARGIN, y - 14,
                "Table: " + tableName + "   ·   Records: " + String.format(Locale.ROOT, "%,d", rowCount)
                        + (continued ? "   (continued)" : ""),
                AuditReportTheme.TEXT_MUTED);
    }

    public static float drawTableHeaderRow(PDPageContentStream cs,
                                           AuditReportPdfFonts fonts,
                                           float y,
                                           float tableWidth,
                                           String[] labels,
                                           int startCol,
                                           int endCol) throws IOException {
        fillRect(cs, AuditReportTheme.MARGIN, y - AuditReportTheme.ROW_H + 2, tableWidth, AuditReportTheme.ROW_H,
                AuditReportTheme.TABLE_HEADER);
        float colW = tableWidth / (endCol - startCol);
        float x = AuditReportTheme.MARGIN;
        for (int i = startCol; i < endCol; i++) {
            text(cs, fonts.bold(), AuditReportTheme.FONT_HEADER, x + 4, y - 10,
                    truncate(labels[i], (int) (colW / 4.5f)), AuditReportTheme.WHITE);
            x += colW;
        }
        return y - AuditReportTheme.ROW_H;
    }

    public static Color rowBackground(boolean alt, boolean warn, boolean error) {
        if (error) {
            return AuditReportTheme.TABLE_ROW_ERROR;
        }
        if (warn) {
            return AuditReportTheme.TABLE_ROW_WARN;
        }
        return alt ? AuditReportTheme.TABLE_ROW_ALT : AuditReportTheme.WHITE;
    }

    // --- drawing primitives ---

    static void text(PDPageContentStream cs, PDFont font, float size, float x, float y, String text, Color color)
            throws IOException {
        cs.setNonStrokingColor(color);
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(x, y);
        cs.showText(AuditReportPdfWriter.sanitizePdfText(text));
        cs.endText();
    }

    private static void drawMetaLine(PDPageContentStream cs, AuditReportPdfFonts fonts, float x, float y,
                                     String label, String value) throws IOException {
        text(cs, fonts.bold(), 10, x, y, label + ":", AuditReportTheme.GOLD);
        text(cs, fonts.regular(), 10, x + 130, y, value, AuditReportTheme.WHITE);
    }

    private static void drawLogo(PDDocument doc, PDPageContentStream cs, AuditReportProperties props,
                                 float x, float y, float maxSize) throws IOException {
        String logoPath = props.getLogoPath();
        if (logoPath == null || logoPath.isBlank() || !Files.exists(Path.of(logoPath.trim()))) {
            return;
        }
        PDImageXObject img = PDImageXObject.createFromFile(logoPath.trim(), doc);
        float scale = Math.min(maxSize / img.getWidth(), maxSize / img.getHeight());
        cs.drawImage(img, x, y, img.getWidth() * scale, img.getHeight() * scale);
    }

    private static Color accentColor(String accent) {
        if (accent == null) {
            return AuditReportTheme.PRIMARY;
        }
        return switch (accent) {
            case "teal" -> AuditReportTheme.TEAL;
            case "gold" -> AuditReportTheme.GOLD;
            case "success" -> AuditReportTheme.SUCCESS;
            case "warning" -> AuditReportTheme.WARNING;
            default -> AuditReportTheme.PRIMARY;
        };
    }

    private static String formatChartValue(double v) {
        if (v >= 1000) {
            return String.format(Locale.ROOT, "₹%,.0f", v);
        }
        return String.format(Locale.ROOT, "%,.0f", v);
    }

    static String truncate(String value, int maxChars) {
        if (value == null) {
            return "";
        }
        if (value.length() <= maxChars) {
            return value;
        }
        return value.substring(0, Math.max(0, maxChars - 1)) + "…";
    }

    private static void fillRect(PDPageContentStream cs, float x, float y, float w, float h, Color c)
            throws IOException {
        cs.setNonStrokingColor(c);
        cs.addRect(x, y, w, h);
        cs.fill();
    }

    private static void fillRoundedRect(PDPageContentStream cs, float x, float y, float w, float h,
                                        float r, Color c) throws IOException {
        // PDFBox simple rect fallback (true rounded rect optional)
        fillRect(cs, x, y, w, h, c);
    }

    private static void strokeRoundedRect(PDPageContentStream cs, float x, float y, float w, float h,
                                          float r, Color c) throws IOException {
        cs.setStrokingColor(c);
        cs.addRect(x, y, w, h);
        cs.stroke();
    }

    private static void strokeLine(PDPageContentStream cs, float x1, float y1, float x2, float y2, Color c)
            throws IOException {
        cs.setStrokingColor(c);
        cs.moveTo(x1, y1);
        cs.lineTo(x2, y2);
        cs.stroke();
    }
}
