-- =============================================================================
-- OPTIONAL — NOT required for normal operation
-- =============================================================================
-- The duplicate-phone error is fixed in application code (CustomerService:
-- reuse existing row by phone before insert). You do NOT need to run this file
-- for that behaviour.
--
-- This script is only for teams who want to align the MySQL schema with
-- (location + phone) uniqueness and drop a legacy UNIQUE(phone) index.
-- If you cannot change the database, skip this file entirely.
-- =============================================================================

-- Example only — verify index names on your DB first (SHOW INDEX FROM customers;)
-- ALTER TABLE customers DROP INDEX UK_m3iom37efaxd5eucmxjqqcbe9;
-- ALTER TABLE customers ADD UNIQUE KEY uk_customer_location_phone (location, phone);
